name: cnvg
channels:
  - conda-forge
  - bioconda
dependencies:
  - biopython=1.86=py314h0612a62_0
  - brotli=1.2.0=hca488c2_0
  - brotli-bin=1.2.0=hce9b42c_0
  - brotli-python=1.2.0=py314h95ef04c_0
  - bzip2=1.0.8=hd037594_8
  - c-ares=1.34.5=h5505292_0
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - certifi=2025.11.12=pyhd8ed1ab_0
  - cffi=2.0.0=py314h44086f9_1
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - contourpy=1.3.3=py314h784bc60_3
  - coreutils=9.5=h93a5062_0
  - curl=8.17.0=hdece5d2_0
  - cycler=0.12.1=pyhcf101f3_2
  - figtree=1.4.4=hdfd78af_1
  - fonttools=4.61.0=pyh7db6752_0
  - freetype=2.14.1=hce30654_0
  - gawk=5.3.1=h8a92848_0
  - gmp=6.3.0=h7bae524_2
  - h2=4.3.0=pyhcf101f3_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=75.1=hfee45f7_0
  - idna=3.11=pyhd8ed1ab_0
  - iqtree=3.0.1=h39b84e0_0
  - kiwisolver=1.4.9=py314h42813c9_2
  - krb5=1.21.3=h237132a_0
  - lcms2=2.17=h7eeda09_0
  - lerc=4.0.0=hd64df32_1
  - libasprintf=0.25.1=h493aca8_0
  - libblas=3.11.0=1_h51639a9_openblas
  - libbrotlicommon=1.2.0=h87ba0bc_0
  - libbrotlidec=1.2.0=h95a88de_0
  - libbrotlienc=1.2.0=hb1b9735_0
  - libcblas=3.11.0=1_hb0561ab_openblas
  - libcurl=8.17.0=hdece5d2_0
  - libcxx=21.1.6=hf598326_0
  - libdeflate=1.25=hc11a715_0
  - libedit=3.1.20250104=pl5321hafb1f1b_0
  - libev=4.33=h93a5062_2
  - libexpat=2.7.3=haf25636_0
  - libffi=3.5.2=he5f378a_0
  - libfreetype=2.14.1=hce30654_0
  - libfreetype6=2.14.1=h6da58f4_0
  - libgettextpo=0.25.1=h493aca8_0
  - libgfortran=15.2.0=hfcf01ff_1
  - libgfortran5=15.2.0=h742603c_1
  - libiconv=1.18=h23cfdf5_2
  - libintl=0.25.1=h493aca8_0
  - libjpeg-turbo=3.1.2=hc919400_0
  - liblapack=3.11.0=1_hd9741b5_openblas
  - liblzma=5.8.1=h39f12f2_2
  - libmpdec=4.0.0=h5505292_0
  - libnghttp2=1.67.0=hc438710_0
  - libopenblas=0.3.30=openmp_ha158390_3
  - libpng=1.6.51=hfab5511_0
  - libsqlite=3.51.0=h8adb53f_0
  - libssh2=1.11.1=h1590b86_0
  - libtiff=4.7.1=h4030677_1
  - libwebp-base=1.6.0=h07db88b_0
  - libxcb=1.17.0=hdb1d25a_0
  - libzlib=1.3.1=h8359307_2
  - llvm-openmp=21.1.6=h4a912ad_0
  - mafft=7.526=h99b78c6_0
  - matplotlib-base=3.10.8=py314hd63e3f0_0
  - mpfr=4.2.1=hb693164_3
  - munkres=1.1.4=pyhd8ed1ab_1
  - ncurses=6.5=h5e97a16_3
  - nextflow=25.10.0=h2a3209d_0
  - numpy=2.3.5=py314h5b5928d_0
  - openjdk=23.0.2=hfb9339a_2
  - openjpeg=2.5.4=hbfb3c88_0
  - openssl=3.6.0=h5503f6c_0
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.3=py314ha3d490a_1
  - pillow=12.0.0=py314h57fbdfe_2
  - pip=25.3=pyh145f28c_0
  - pthread-stubs=0.4=hd74edd7_1002
  - pycparser=2.22=pyh29332c3_1
  - pyparsing=3.2.5=pyhcf101f3_0
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.14.0=h40d2674_102_cp314
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.14=8_cp314
  - pytz=2025.2=pyhd8ed1ab_0
  - qhull=2020.2=h420ef59_5
  - readline=8.2=h1d1bf99_2
  - requests=2.32.5=pyhd8ed1ab_0
  - scipy=1.16.3=py314h624bdf2_1
  - six=1.17.0=pyhe01879c_1
  - tk=8.6.13=h892fb3f_3
  - treetime=0.11.4=pyhdfd78af_0
  - tzdata=2025b=h78e105d_0
  - unicodedata2=17.0.0=py314h0612a62_1
  - urllib3=2.5.0=pyhd8ed1ab_0
  - xorg-libx11=1.8.12=h6a5fb8c_0
  - xorg-libxau=1.0.12=hc919400_1
  - xorg-libxdmcp=1.1.5=hc919400_1
  - xorg-libxext=1.3.6=hd74edd7_0
  - xorg-libxfixes=6.0.2=hc919400_0
  - xorg-libxi=1.8.2=hd74edd7_0
  - xorg-libxtst=1.2.5=hd74edd7_3
  - zlib-ng=2.3.2=h248ca61_0
  - zstandard=0.25.0=py314h9d33bd4_1
  - zstd=1.5.7=h6491c7d_2
prefix: /opt/homebrew/Caskroom/miniforge/base/envs/cnvg
