name: cnvg
channels:
  - conda-forge
  - bioconda
dependencies:
  - c-ares=1.34.5=h5505292_0
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - coreutils=9.5=h93a5062_0
  - curl=8.17.0=hdece5d2_0
  - gawk=5.3.1=h8a92848_0
  - gmp=6.3.0=h7bae524_2
  - krb5=1.21.3=h237132a_0
  - libasprintf=0.25.1=h493aca8_0
  - libcurl=8.17.0=hdece5d2_0
  - libcxx=21.1.6=hf598326_0
  - libedit=3.1.20250104=pl5321hafb1f1b_0
  - libev=4.33=h93a5062_2
  - libgettextpo=0.25.1=h493aca8_0
  - libiconv=1.18=h23cfdf5_2
  - libintl=0.25.1=h493aca8_0
  - libnghttp2=1.67.0=hc438710_0
  - libssh2=1.11.1=h1590b86_0
  - libzlib=1.3.1=h8359307_2
  - mafft=7.526=h99b78c6_0
  - mpfr=4.2.1=hb693164_3
  - ncurses=6.5=h5e97a16_3
  - nextflow=25.10.0=h2a3209d_0
  - openjdk=23.0.2=hfb9339a_2
  - openssl=3.6.0=h5503f6c_0
  - readline=8.2=h1d1bf99_2
  - zstd=1.5.7=h6491c7d_2
prefix: /opt/homebrew/Caskroom/miniforge/base/envs/cnvg
